### ISSUE TITLE
import transport error

### ISSUE THREAD

**Issue by 3cl1ps** [LefterisJP/eth2_deposit_tx_maker#1]
hey,
npm install did finish fine but on the next step i got : 
```
 nodemon --exec babel-node main.js "0" "ffffffffffffff"

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node main.js 0 ffffffffffffff`
/home/thomas/eth2_deposit_tx_maker/main.js:1
import Transport from "@ledgerhq/hw-transport-node-hid";
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (/home/thomas/eth2_deposit_tx_maker/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/home/thomas/eth2_deposit_tx_maker/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at Object.<anonymous> (/home/thomas/eth2_deposit_tx_maker/node_modules/@babel/node/lib/_babel-node.js:174:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by 3cl1ps** [comment]
made it work by :
changing node version : v15
add   "type": "module", in package.json
and finally this one : https://github.com/LedgerHQ/ledgerjs/issues/140

**Comment by LefterisJP** [comment]
Hey @3cl1ps thanks for letting me know. Yeah this is a quick script I put here. "worked on my system".

I guess there is a min version of nodejs required
